version: '3.8'

services:
  jellyfin-discord-notifier:
    image: ghcr.io/moldytaint/jellyfindiscordupdates:main
    container_name: jellyfin-discord-notifier
    volumes:
      - ./Config:/app/data
      - ./.env:/app/.env:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TIMEZONE:-UTC}
    restart: unless-stopped